python launch_slurm_array.py \
  --raw-data-path /home/tilman/bees1/private/tilman/nanoseq_batch4/data/raw/files/P38907 \
  --detag-path /home/tilman/bees1/private/tilman/nanoseq_batch4/data/detag \
  --bam-folder /home/tilman/bees1/private/tilman/nanoseq_batch4/data/bams \
  --dupcaller-path ~/miniforge3/bin/DupCaller.py \
  --ref-fasta /home/tilman/bees1/private/tilman/nanoseq_batch4/data/somatic_aux_data/ref/GCF_003254395.2_Amel_HAv3.1_genomic.fna \
  --max-parallel 99 \
  --slurm-cpus-per-task 8 \
  --job-name nanoseq_process \
  --project-id UPPMAX2025-2-481 \
  --env base
